### ISSUE TITLE
Which kernel config should I modify?

### ISSUE THREAD

**Issue by JonasVautherin** [GloDroidCommunity/pine64-pinephone#39]
I would like to add a config (`CONFIG_USB_IPHETH=y`) and rebuild the kernel. But I am not sure which file I should edit.

I first thought `amlogic_defconfig` (which is apparently patched [here](https://github.com/GloDroidCommunity/pine64-pinephone/blob/main/patches-aosp/glodroid/configuration/0005-kconfig-Sync-android-base-config-with-kernel-configs.patch)), but it already contains `CONFIG_USB_IPHETH=m` and it doesn't seem to build `ipheth.ko`, so I feel like I am missing something. Also in the result, I see stuff like:

```
./obj/GLODROID/KERNEL/build/.config:# CONFIG_USB_IPHETH is not set
```

@rsglobal would you have some insights? 😇

**Comment by rsglobal** [comment]
Sure, try to modify the aosptree/vendor/devices-community/pine64_pinephone/kernel.defconfig file and see if ./obj/GLODROID/KERNEL/build/.config changes.

**Comment by JonasVautherin** [comment]
Thanks!

Interestingly, I set `CONFIG_USB_IPHETH=y` in `aosptree/vendor/devices-community/pine64_pinephone/kernel.defconfig`, run `build.sh` and end up with... `CONFIG_USB_IPHETH=m` in `./obj/GLODROID/KERNEL/build/.config` 😅🤔

It's better than nothing, but it's not what I was expecting...

**Comment by rsglobal** [comment]
Likely, some parent config is set to the module, forcing all child configs to be modules.

**Comment by JonasVautherin** [comment]
Oh, right. That makes sense indeed!

Thanks a lot for the help! :rocket:
